# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0003_auto_20160301_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='', verbose_name='\u56fe\u7247', width_field=60),
        ),
    ]
