# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0004_auto_20160302_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(blank=True, height_field='100px', null=True, upload_to='', verbose_name='\u56fe\u7247', width_field='60px'),
        ),
    ]
