# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0009_auto_20160302_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='height',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='book',
            name='width',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
