# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0010_auto_20160302_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.CharField(max_length=50, null=True, verbose_name='\u6587\u7ae0\u63cf\u8ff0'),
        ),
    ]
