# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0011_book_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.TextField(max_length=50, null=True, verbose_name='\u6587\u7ae0\u4ecb\u7ecd'),
        ),
    ]
