# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0012_auto_20160302_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='nickname',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=128, verbose_name='\u4f5c\u8005'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(max_length=128, verbose_name='\u5206\u7c7b'),
        ),
        migrations.AlterField(
            model_name='book',
            name='height',
            field=models.PositiveIntegerField(default=100, verbose_name='\u9ad8\u5ea6'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.FloatField(verbose_name='\u4ef7\u683c'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateField(verbose_name='\u51fa\u7248\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='book',
            name='width',
            field=models.PositiveIntegerField(default=60, verbose_name='\u5bbd\u5ea6'),
        ),
    ]
