# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0014_remove_book_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='nickname',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
