# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0019_auto_20160309_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='bookname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mycart',
        ),
        migrations.AddField(
            model_name='cart',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BookStore.Book'),
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
