# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-13 06:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0021_user_mycart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mycart',
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
