# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-16 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0024_auto_20160316_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.UUIDField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
